image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - deploy

deploy:
    stage: deploy
    only:
        - master
    script:
        - echo THIS WANTS TO BE VERSION $CI_BUILD_ID
        - dotnet build -c release
        - dotnet test -c release
        - dotnet pack src/**/*.fsproj -c release -o ./pack --version-suffix $CI_JOB_ID
        - dotnet nuget push **/*.nupkg -k $NugetAPIKey
    artifacts:
      paths:
        - "bin/*.nupkg"