image: microsoft/dotnet:latest

stages:
    - build

build:
    stage: build
    script:
        - "dotnet pack -c release -o ../../bin src/Thorocaine/Thorocaine.csproj"
        - "dotnet pack -c release -o ../../bin src/Thorocaine.Console/Thorocaine.Cli.csproj"
    artifacts:
      paths:
        - "bin/*.nupkg"
