image: microsoft/dotnet:latest

stages:
    - build
    - test
    - deploy

build:
    stage: build
    only:
        - master
    script:
        - 'dotnet build -c release'

test:
    stage: test
    only:
        - master
    script:
        - 'dotnet test -c release'

deploy:
    stage: deploy
    only:
        - master
    script:
        - 'echo THIS WANTS TO BE VERSION 1.0.%CI_BUILD_ID%'
        - 'dotnet pack src/**/*.csproj -c release -o ./pack -Version 1.0.%CI_BUILD_ID%'
        - 'dotnet nuget push ./pack/*.nupkg -k %NugetAPIKey%'
    artifacts:
      paths:
        - "bin/*.nupkg"