image: microsoft/dotnet:latest

stages:
    - build-Core
    - build-cli
#    - test

build:
    stage: build-Core
    script:
        - "dotnet build src/Thorocaine/Thorocaine.csproj"
    artifacts:
      paths:
        - bin/

build:
    stage: build-cli
    script:
        - "dotnet build src/Thorocaine.Console/Thorocaine.Cli.csproj"
    artifacts:
      paths:
        - bin/

# test:
#    stage: test
#    script: 
#        - "dotnet test"
